### ISSUE TITLE
Partially accepted Purchases

### ISSUE THREAD

**Issue by Mitrimo** [g3n35i5/shop-db2#21]
When buying multiple products, the system apparently checks the validity for each article separately.
Example: When buying a crate of beer (x30) and "buying" the return value of the crate (Pfand) while not having enough funds to buy the beer (e. g. the account is too close to the - 20€ limit), the system rejects the beer puchase but logs the return fee, resulting in a net gain for the user account without a notification message.

**Comment by g3n35i5** [comment]
Thanks for the bug report.

I would consider this as a frontend-related issue, because it is checked whether the total credit is sufficient for all purchases. However, if the purchases are inserted one after the other, their order is relevant. They must be sorted by purchase price in ascending order so that negative amounts are entered first and thus the credit is sufficient at the end. 

Please have a look at the [frontend issue](https://github.com/g3n35i5/shop-db2-frontend/issues/7)
